#! /bin/sh

# make matlab work properly
# REF: https://wiki.archlinux.org/title/MATLAB
# java application common issue mentioned in ref
export _JAVA_AWT_WM_NONREPARENTING=1
# 通过测试发现：上面这一行命令必须放到所有异步命令的前面，环境变量才能
# 被正常设置所谓的异步是指：以 & 结尾的命令，例如，下文就有三个异步命
# 令，分别是:
# sxhkd &
# exec ~/.nutstore/dist/bin/nutstore-pydaemon.py &
# exec /home/yongfeizhai/.config/i3/tap-to-click.sh &

# 另外一个解决方案，在 ~/.profile 的文件尾追加下面这几行命令即可
# if [ $XDG_SESSION_DESKTOP = "bspwm" ]; then
#     export _JAVA_AWT_WM_NONREPARENTING=1
# fi

sxhkd &
$HOME/.fehbg

# autostart
exec ~/.nutstore/dist/bin/nutstore-pydaemon.py &
exec /home/yongfeizhai/.config/i3/tap-to-click.sh &

setxkbmap -option ctrl:nocaps

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
