#!/bin/bash

win_class=$1

# 现在有一个问题：如果不加 --onlyvisible 这个 flag 的话，会返回多个 window id(很奇怪，因为我只有一个 window ，他给我返回了好几个结果，不知道怎么处理)
all_window=$(xdotool search --class --onlyvisible $win_class )

activate_window=$(xdotool getactivewindow)
echo $activate_window
# echo $win_list | sed "s/.*$active_win_id//" | awk '{print $1}'
target_window=$(echo $all_window | sed "s/$activate_window//" | awk '{print $1}')
echo $target_window

if [ "$target_window" == '' ];then
   target_window=$(echo $all_window | awk '{print $1}')
fi

xdotool windowactivate $target_window
